# Generated by Django 4.1 on 2023-07-02 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_customuser_category_customuser_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existingmedcondition', models.BooleanField(default=False)),
                ('takingmedications', models.BooleanField(default=False)),
                ('anyallergies', models.BooleanField(default=False)),
                ('previoussurgeries', models.BooleanField(default=False)),
                ('familymedhistory', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('drinker', models.BooleanField(default=False)),
                ('exercise', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
