# Generated by Django 4.1 on 2023-07-03 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_medicalinformation_covid_medicalinformation_diabetes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normal_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='category',
            field=models.CharField(choices=[('health_worker', 'HEALTH_WORKER'), ('normal_patient', 'NORMAL_PATIENT')], default=1, max_length=50),
        ),
    ]
